agf/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.Index,  name='home'),
    path('profile', views.Profile,  name='profile'),

    # Built in
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),

    # Documents
    path('documents/', include('agf_documents.urls')),

    # Assets
    path('assets/', include('agf_assets.urls')),

    # HSE
    path('hse/', include('agf_hse.urls')),
    
    # Maintenance
    path('maintenance/', include('agf_maintenance.urls')),

    # Stores
    path('stores/', include('agf_stores.urls')),

    # WIMS
    path('wims/', include('agf_wims.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agf_maintenance/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.Dashboard, name='maintenance'),
    path('pm', views.PM_List, name='pm_list'),
    path('pm/<int:id>/', views.PM_view, name='pm'),
    path('procedure/<int:id>/', views.Procedure_view, name='procedure'),
    path('wo', views.WO_List, name='wo_list'),
    path('wo/<int:id>/', views.WO_view, name='wo'),
    

    path('deployPM/<int:id>/', views.DeployWO, name='deployPM'),
    path('deployProcedure/<int:pid>/<int:aPMid>/', views.DeployProcedure, name='deployProcedure'),
    path('deployAll/', views.DeployAll),
    path('disableAssetPM/<int:id>/', views.DisableAssetPM, name='disableAssetPM'),
    path('enableAssetPM/<int:id>/', views.EnableAssetPM, name='enableAssetPM'),

    path('completeWO/<int:id>/', views.CompleteWO, name='completeWO'),
    
    path('attachMaintenanceDocument/<int:id>/', views.AttachMaintenanceDocument, name='attachMaintenanceDocument'),
]

agf_files/models.py
from datetime import datetime
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse

# Other module imports
from agf_documents.models import *
from agf_assets.models import *

# Third Part Imports.
from datetime import date

# Files
class File (models.Model):
    location=models.CharField(max_length=1000)
    ext=models.CharField(max_length=10)
    name=models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}.{self.ext}"

    @property
    def name_ext(self):
        return f"{self.name}.{self.ext}"

    @property
    def link(self):
        return f"{self.location}{self.name}.{self.ext}"

    def url(self):
        location=self.location
        if location[0] == '\\':
            location = location[1:]
        return f"{settings.MEDIA_URL}{location}{self.name}.{self.ext}"

class FileMeta(models.Model):
    file=models.OneToOneField(File, on_delete=models.CASCADE, related_name='file_metadata')
    created=models.DateTimeField(default=datetime.now)
    modified=models.DateTimeField(default=datetime.now)
    size=models.IntegerField(null=True, blank=True)
    created_by=models.ForeignKey(User, on_delete=models.RESTRICT, related_name='created_files')
    modified_by=models.ForeignKey(User, on_delete=models.RESTRICT, related_name='modified_files')

class DocumentFile (models.Model):
    document_revision=models.ForeignKey(DocumentRevision, on_delete=models.CASCADE, related_name='document_files')
    file=models.ForeignKey(File, on_delete=models.RESTRICT, related_name='file_document')
    public_link=models.CharField(max_length=255, null=True, blank=True, unique=True)
    link_expiry=models.DateField(null=True, blank=True)

    @property
    def get_public_link(self):
        print("here1")
        if self.link_expiry is not None:
            print("here")
            print(self.link_expiry)
            print(self.public_link)
            if date.today() < self.link_expiry:
                return reverse('documet_public_link', kwargs={'link':self.public_link})
            else:
                return None
        else:
            return None

class Image (models.Model):
    file=models.ForeignKey(File, on_delete=models.RESTRICT, related_name='file_image')
    pw = models.IntegerField(null=True, blank=True)
    ph = models.IntegerField(null=True, blank=True)

class AssetImage (models.Model):
    image=models.ForeignKey(Image, on_delete=models.RESTRICT, related_name='image_assets')
    asset=models.ForeignKey(Asset, on_delete=models.RESTRICT, related_name='asset_images')
    display=models.BooleanField(default=False) # Is this the main display picture of the asset
    nameplate=models.BooleanField(default=False) # Is this the nameplate picture

agf_maintenance/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator 
from django.db.models import Max

# Other module imports
from agf_assets.models import *
from agf_documents.models import *

# Third party import
from datetime import date
from dateutil.relativedelta import relativedelta
import math 

# Preventative Maintenance
class PM(models.Model):
    SCHEDULE = 1
    ROTATING = 2

    TYPE = (
        (SCHEDULE, _('Schedule')),
        (ROTATING, _('Rotating Equipment')),
    )

    HRS = 0
    DAYS = 1
    WEEKS = 2
    MONTHS = 3

    UNITS = (
        (HRS, _('hours')),
        (DAYS, _('days')),
        (WEEKS, _('weeks')),
        (MONTHS, _('months')),
    )

    SUPRESSION = 1
    SIMPLE = 2

    SCHEDULE_TYPE = (
        (SUPRESSION, _('Supression')),
        (SIMPLE, _('Simple Schedule')),
    )

    name = models.CharField(max_length=1000)
    type = models.PositiveSmallIntegerField(choices=TYPE)
    units = models.PositiveSmallIntegerField(choices=UNITS)
    frequency = models.IntegerField()
    sch_type = models.PositiveSmallIntegerField(choices=SCHEDULE_TYPE)
    force_sch = models.BooleanField() # Ignores last complete and sticks to schedule
    sch_ahead = models.IntegerField() # Always in weeks

    def __str__(self):
        mstr = str(self.frequency)
        if self.units == self.HRS:
            mstr += "Hr"
        if self.units == self.DAYS:
            mstr += "D"
        if self.units == self.WEEKS:
            mstr += "W"
        if self.units == self.MONTHS:
            mstr += "M"

        mstr += " " + self.name

        return mstr
    
    @property
    def units_short(self):
        mstr = "error"
        if self.units == self.HRS:
            mstr = "HR"
        if self.units == self.DAYS:
            mstr = "D"
        if self.units == self.WEEKS:
            mstr = "W"
        if self.units == self.MONTHS:
            mstr = "M"
        
        return mstr

    @property
    def title(self):
        mstr = str(self.frequency)
        if self.units == self.HRS:
            mstr += "Hr"
        if self.units == self.DAYS:
            mstr += "D"
        if self.units == self.WEEKS:
            mstr += "W"
        if self.units == self.MONTHS:
            mstr += "M"

        name = self.name.upper()

        title = f"{mstr} {name}"

        return title

    @property
    def pmid(self):
        return f"PM{self.id:04}"


    @property
    def get_frequency_long(self):
        mstr = str(self.frequency)
        if self.units == self.HRS:
            mstr += " hours"
        if self.units == self.DAYS:
            mstr += " days"
        if self.units == self.WEEKS:
            mstr += " weeks"
        if self.units == self.MONTHS:
            mstr += " months"

        return mstr

    @property
    def get_frequency_short(self):
        mstr = str(self.frequency)
        if self.units == self.HRS:
            mstr += "Hr"
        if self.units == self.DAYS:
            mstr += "D"
        if self.units == self.WEEKS:
            mstr += "W"
        if self.units == self.MONTHS:
            mstr += "M"

        return mstr

    def get_procedures(self):
        procedures = []
        if self.sch_type == self.SUPRESSION:
            schds = self.procedures.all()
            max = schds.aggregate(Max('sequence'))
            max = max['sequence__max']

            if max:
                for i in range(1,max+1,1):
                    procedure = None
                    for schd in schds:
                        if i % schd.sequence == 0:
                            procedure = schd.procedure
                    if procedure:
                        procedures.append(procedure)

        if self.sch_type == self.SIMPLE:
            schds = self.procedures.all()
            for schd in schds:
                procedures.append(schd.procedure)

        return procedures

class Procedure(models.Model):
    name = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

class ProcedureSchedule(models.Model):
    pm = models.ForeignKey(PM, on_delete=models.CASCADE, related_name="procedures")
    procedure = models.ForeignKey(Procedure, on_delete=models.CASCADE, related_name="pms")
    sequence = models.PositiveIntegerField()

    class Meta:
        ordering = ['sequence']

    def __str__(self):
        return self.get_frequency_short

    @property
    def get_frequency_long(self):
        mstr = str(self.pm.frequency*self.sequence)
        if self.pm.units == self.pm.HRS:
            mstr += " hours"
        if self.pm.units == self.pm.DAYS:
            mstr += " days"
        if self.pm.units == self.pm.WEEKS:
            mstr += " weeks"
        if self.pm.units == self.pm.MONTHS:
            mstr += " months"

        return mstr

    @property
    def get_frequency_short(self):
        mstr = str(self.pm.frequency*self.sequence)
        if self.pm.units == self.pm.HRS:
            mstr += "Hr"
        if self.pm.units == self.pm.DAYS:
            mstr += "D"
        if self.pm.units == self.pm.WEEKS:
            mstr += "W"
        if self.pm.units == self.pm.MONTHS:
            mstr += "M"

        return mstr


class AssetPM(models.Model):
    pm = models.ForeignKey(PM, on_delete=models.RESTRICT, related_name="assets")
    asset=models.ForeignKey(Asset, on_delete=models.RESTRICT, related_name="pms")
    enabled=models.BooleanField()
    utilisation = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], null=True, blank=True)
    last_procedure = models.PositiveIntegerField()
    last_complete = models.DateField()
    last_deployed = models.DateField()
 
    def __str__(self):
        return f"{self.pm} ({self.asset})"

    @property
    def next_procedure_sch(self):
        current_id = self.last_procedure
        next_procedure_sch = ProcedureSchedule.objects.filter(pm=self.pm, sequence__gte = current_id).order_by('sequence').first()

        if next_procedure_sch is None:
            next_procedure_sch = ProcedureSchedule.objects.filter(pm=self.pm).order_by('sequence').first()

        return next_procedure_sch
    
    @property
    def next_date(self):
        frequency = self.pm.frequency
        if self.pm.type == self.pm.ROTATING and self.pm.units == self.pm.HRS:
            if self.utilisation:
                frequency = round(frequency*self.utilisation*0.041666667,0)
                if self.pm.force_sch:
                    next = self.last_deployed + relativedelta(days=+frequency)
                else:
                    next = self.last_complete + relativedelta(days=+frequency)

        elif self.pm.units == self.pm.DAYS:
            if self.pm.force_sch:
                next = self.last_deployed + relativedelta(days=+frequency)
            else:
                next = self.last_complete + relativedelta(days=+frequency)

        elif self.pm.units == self.pm.WEEKS:
            if self.pm.force_sch:
                next = self.last_deployed + relativedelta(weeks=+frequency)
            else:
                next = self.last_complete + relativedelta(weeks=+frequency)

        elif self.pm.units == self.pm.MONTHS:
            if self.pm.force_sch:
                next = self.last_deployed + relativedelta(months=+frequency)
            else:
                next = self.last_complete + relativedelta(months=+frequency)

        else:
            return None
        
        return next

    @property
    def next_deploy(self):
        frequency = self.pm.frequency
        if self.pm.type == self.pm.ROTATING and self.pm.units == self.pm.HRS:
            if self.utilisation:
                frequency = round(frequency*self.utilisation*0.041666667,0)
                if self.pm.force_sch:
                    next = self.last_deployed + relativedelta(days=+frequency)
                else:
                    next = self.last_complete + relativedelta(days=+frequency)

        elif self.pm.units == self.pm.DAYS:
            if self.pm.force_sch:
                next = self.last_deployed + relativedelta(days=+frequency)
            else:
                next = self.last_complete + relativedelta(days=+frequency)

        elif self.pm.units == self.pm.WEEKS:
            if self.pm.force_sch:
                next = self.last_deployed + relativedelta(weeks=+frequency)
            else:
                next = self.last_complete + relativedelta(weeks=+frequency)

        elif self.pm.units == self.pm.MONTHS:
            if self.pm.force_sch:
                next = self.last_deployed + relativedelta(months=+frequency)
            else:
                next = self.last_complete + relativedelta(months=+frequency)

        else:
            return None
        
        next = next + relativedelta(weeks=-self.pm.sch_ahead)
        
        return next

    @property
    def pmid(self):
        return self.pm.pmid
    
    @property
    def pm_title(self):
        return self.pm.title
    
    @property
    def asset_no(self):
        return self.asset.get_full_asset_no
    
    @property
    def asset_name(self):
        return self.asset.name
    

class WorkOrder(models.Model):
    IMMEDIATE = 1
    URGENT = 2
    NORMAL = 3

    PRIORITIES = (
        (IMMEDIATE, _('Immediate')),
        (URGENT, _('Urgent')),
        (NORMAL, _('Normal')),
    )

    DEPLOYED = 1
    ONHOLD = 2
    COMPLETED = 3
    CANCELLED = 9

    STATUS = (
        (DEPLOYED, _('Deployed')),
        (ONHOLD, _('On Hold')),
        (COMPLETED, _('Completed')),
        (CANCELLED, _('Cancelled')),
    )

    name = models.CharField(max_length=1000)
    pm = models.ForeignKey(AssetPM, null=True, blank=True, on_delete=models.RESTRICT, related_name="wos")
    asset = models.ForeignKey(Asset, on_delete=models.RESTRICT, related_name="wos")
    priority = models.PositiveSmallIntegerField(choices=PRIORITIES)

agf_maintenance/templates/agf_maintenance/pm.html
{% extends 'agf_maintenance/base.html' %}
{% block title %}
{{pm.title}}
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <!-- Title -->
                    <h2>PM{{pm.id|stringformat:"04d"}}: {{pm.name}}</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-bottom: 12px;">
        <div class="col-4">
            <div class="card" style="height:100%;">
                <div class="card-body">
                    <!-- Procedures -->
                    <h4>Procedures</h4>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Sequence</th>
                            <th>Due At</th>
                            <th>Procedure</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        {% for procedure in procedures %} 
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{% widthratio forloop.counter 1 pm.frequency %} {{pm.get_units_display}}</td>
                            <td class="link" onclick="window.location.href='{% url 'procedure' procedure.id %}'">{{procedure.name}}</td>
                            <td>
                                <select id="procedureSelect{{procedure.id}}" onchange="CreateWoUpdate({{procedure.id}})">
                                    {% for assetPM in pm.assets.all %}
                                    <option value="{{assetPM.id}}">{{assetPM.asset.get_full_asset_no}}</option>
                                    {% endfor %}
                                </select>
                                <a id="procedureAction{{procedure.id}}" class="btn btn-primary" href="{% url 'deployProcedure' procedure.id pm.assets.first.id %}">Create WO</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card" style="height:100%;">
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <td colspan="8" style="border-bottom-color:black;"><h4>Enabled Assets</h4></td>
                        </tr>
                        <tr>
                            <th rowspan="2" style="text-align:center; vertical-align: middle; border-bottom-color:black;">Asset</th>
                            <th colspan="2" style="text-align:center; vertical-align: middle;">Last WO</th>
                            <th colspan="2" style="text-align:center; vertical-align: middle;">Next Procedure</th>
                            <th colspan="2" style="text-align:center; vertical-align: middle;">Next WO</th>
                            <th rowspan="2" style="text-align:center; vertical-align: middle; border-bottom-color:black;">Actions</th>
                        </tr>
                        <tr>
                            <th style="text-align:center;">WO ID</th>
                            <th style="text-align:center;">Completed On</th>
                            <th style="text-align:center;">Sequence ID</th>
                            <th>Procedure</th>
                            <th style="text-align:center;">WO ID</th>
                            <th style="text-align:center;">Scheduled Date</th>
                        </tr>
                        </thead>
                        {% for assetpm in pm.assets.all %}
                        {% if assetpm.enabled %}
                        <tr>
                            <td class="link" style="vertical-align: middle;" onclick="window.location.href='{% url 'asset' assetpm.asset.id %}'">{{assetpm.asset.get_name}} ({{assetpm.asset.get_full_asset_no}})</td>
                            <th style="text-align:center; vertical-align: middle;"></th>
                            <td style="text-align:center; vertical-align: middle;">{{assetpm.last_complete}}</td>
                            <td style="text-align:center; vertical-align: middle;">{{assetpm.next_procedure_sch.sequence}}</td>
                            <td style="vertical-align: middle;">{{assetpm.next_procedure_sch.procedure}}</td>
                            
                            {% for object in nextWOs %}
                            {% if object.asset == assetpm.asset %}
                            {% if object.WO %}
                            <td style="text-align:center; vertical-align: middle;"><a class='linkFormat' href="{% url 'wo' object.WO.id %}">{{object.WO.woid}}</a></td>
                            {% else %}
                            <td style="text-align:center; vertical-align: middle;">Not yet deployed</td>
                            {% endif %}
                            {% if object.WO %}
                            <td style="text-align:center; vertical-align: middle;">{{object.WO.sch_date}}</td>
                            {% else %}
                            <td style="text-align:center; vertical-align: middle;">{{assetpm.next_date}}</td>
                            {% endif %}
                            {% endif %}
                            {% endfor %}

                            
                            

                            <td style="text-align:center; vertical-align: middle;">
                                <a class="btn btn-primary" href="{% url 'deployPM' assetpm.id %}">Deploy</a>
                                <a class="btn btn-primary" href="{% url 'disableAssetPM' assetpm.id %}">Disable</a>
                            </td>
                        </tr>
                        {% endif %}
                        {% endfor %}

                        <tr><td colspan="6" style="height:50px;"></td></tr>

                        <thead>
                        <tr>
                            <td colspan="6" style="border-bottom-color:black;"><h4>Disabled Assets</h4></td>
                        </tr>
                        <tr>
                            <th rowspan="2" style="text-align:center; vertical-align: middle; border-bottom-color:black;">Asset</th>
                            <th colspan="2" style="text-align:center; vertical-align: middle;">Last WO</th>
                            <th colspan="2" style="text-align:center; vertical-align: middle;">Next Procedure</th>
                            <th rowspan="2" style="text-align:center; border-bottom-color:black;">Actions</th>
                        </tr>
                        <tr>
                            <th style="text-align:center; border-bottom-color:black;">WO ID</th>
                            <th style="text-align:center; border-bottom-color:black;">Completed On</th>
                            <th style="text-align:center; border-bottom-color:black;">Sequence ID</th>
                            <th style="border-bottom-color:black;">Procedure</th>
                        </tr>
                        </thead>
                        {% for assetpm in pm.assets.all %}
                        {% if not assetpm.enabled %}
                        <tr style="color:red;">
                            <td class="link" style="vertical-align: middle;" onclick="window.location.href='{% url 'asset' assetpm.asset.id %}'">{{assetpm.asset.get_name}} ({{assetpm.asset.get_full_asset_no}})</td>
                            <th style="text-align:center; vertical-align: middle;"></th>
                            <td style="text-align:center; vertical-align: middle;">{{assetpm.last_complete}}</td>
                            <td style="text-align:center; vertical-align: middle;">{{assetpm.next_procedure_sch.sequence}}</td>
                            <td style="vertical-align: middle;">{{assetpm.next_procedure_sch.procedure}}</td>
                            <td style="text-align:center; vertical-align: middle;"><a class="btn btn-primary" href="{% url 'enableAssetPM' assetpm.id %}">Enable</a></td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h2>Work Order List</h2>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Status</th>
                                <th>Name</th>
                                <th>Asset</th>
                                <th>Scheduled Date</th>
                                <th>Completed Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for wo in wos %}
                            <tr class="link" onclick="window.location.href='{% url 'wo' wo.id %}'">
                                <td>{{wo.woid}}</td>
                                <td>{{wo.get_status_display}}</td>
                                <td>{{wo.name}}</td>
                                <td>{{wo.asset}}</td>
                                <td>{{wo.sch_date}}</td>
                                <td>{{wo.complete_date}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    function CreateWoUpdate(id){
        selectEl = document.getElementById('procedureSelect'+id);
        anchorEl = document.getElementById('procedureAction'+id);

        value = selectEl.options[selectEl.selectedIndex].value;

        var url_mask = "{% url 'deployProcedure' pid=6789 aPMid=12345 %}".replace(/12345/, value.toString()).replace(/6789/, id.toString());

        anchorEl.href = url_mask;
    }
</script>

{% endblock %}

agf_maintenance/templates/agf_maintenance/workorder.html
{% extends 'agf_maintenance/base.html' %}
{% block title %}
WO{{wo.id|stringformat:"05d"}}
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <!-- WO Title -->
                    <h2>WO{{wo.id|stringformat:"05d"}}: {{wo.name}}</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-bottom: 12px;">
        <div class="col-4">
            <div class="card" style="height:100%;">
                <div class="card-body">
                    <!-- WO Details -->
                    <table class="table">
                        {% if not wo.pm %}
                        <tr>
                            <th>Type</th>
                            <td>Corrective Maintenance</td>
                        </tr>
                        {% else %} 
                        <tr>
                            <th>Type</th>
                            <td>Preventative Maintenance</td>
                        </tr>
                         <tr>
                            <th>PM</th>
                            <td class="link" onclick="window.location.href='{% url 'pm' wo.pm.pm.id %}'">{{wo.pm.pm.pmid}}: {{wo.pm.pm.name}}</td>
                         </tr>
                        {% endif %}

                         <tr>
                            <th>Asset</th>
                            <td class="link" onclick="window.location.href='{% url 'asset' wo.asset.id %}'">{{wo.asset.get_full_asset_no}}: {{wo.asset.get_name}}</td>
                         </tr>

                        <tr>
                            <th>Status</th>
                            <td>{{wo.get_status_display}}</td>
                        </tr>
                        <tr>
                            <th>Priority</th>
                            <td>{{wo.get_priority_display}}</td>
                        </tr>
                        <tr>
                            <th>Schedule Date</th>
                            <td>{{wo.sch_date}}</td>
                        </tr>
                        {% if wo.status == wo.COMPLETED %}
                        <tr>
                            <th>Completed Date</th>
                            <td>{{wo.complete_date}}</td>
                        </tr>
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card" style="height:100%;">
                <div class="card-body">
                    <!--- Tasks -->
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Sequence ID</th>
                                <th>Task</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for woTask in wo.tasks.all %}
                            <tr>
                                <td>{{woTask.no}}</td>
                                {% autoescape off %}
                                <td>{{woTask.task}}</td>
                                {% endautoescape %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body"> 
                    <!-- Actions -->
                    <h2>Actions</h2>
                    {% if wo.status == wo.DEPLOYED %}
                    <a class='btn btn-primary' href='{% url 'completeWO' wo.id %}'>Complete</a>
                    {% endif %}
                    
                    {% if wo.status != wo.DEPLOYED %}
                    <a class='btn btn-primary' href='#'>Redeploy (under development)</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body"> 
                    <!-- Attachments -->
                    <h2>Attachments</h2>
                    <table class="table table-striped" style="width: auto; min-width: 40vw;">
                        {% for wodoc in wo.documents.all %}
                        {% with wodoc.document.revisions.last as rev %}
                        <tr>
                            {% if wodoc.document.type.code == "MAIN" %}
                            <td style="vertical-align: middle;">   
                                {{rev.file_name}}
                            </td>
                            {% else %}
                            <td style="vertical-align: middle;" class="link" onclick=" window.location.href='{% url 'document' wodoc.document.id %}'">
                                {{wodoc.document}}
                            </td>
                            {% endif %}
                            
                            <td style="vertical-align: middle;">
                                {% if rev.my_link == "#" %}
                                <a class="btn btn-primary" href="{% url 'document' id=wodoc.document.id %}">View Document</a>
                                {% else %}
                                <a class="btn btn-primary" href="{{wodoc.document.revisions.last.my_link}}" target="blank" download>Download</a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endwith %}
                        {% endfor %}
                    </table>
                    <br>
                    <hr>
                    <!-- Add attachments -->
                    <form action="{% url 'attachMaintenanceDocument' id=wo.id %}" enctype="multipart/form-data" method="POST">
                        {% csrf_token %}
                        <label for="id_file">Upload a file:</label>
                        <input type="file" name="file" required="" id="id_file">
                        <input class="btn btn-primary" type="submit" value="Upload">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}