agf/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.Index,  name='home'),
    path('profile', views.Profile,  name='profile'),

    # Built in
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),

    # Documents
    path('documents/', include('agf_documents.urls')),

    # Assets
    path('assets/', include('agf_assets.urls')),

    # HSE
    path('hse/', include('agf_hse.urls')),
    
    # Maintenance
    path('maintenance/', include('agf_maintenance.urls')),

    # Stores
    path('stores/', include('agf_stores.urls')),

    # WIMS
    path('wims/', include('agf_wims.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agf_wims/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('wells', views.WellPage, name='wells'),
]

agf/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

# Environmental Protaction Agency Permit
class EPA(models.Model):
    permit_no=models.CharField(max_length=255)
    security_held=models.DecimalField(
        max_digits=8, 
        decimal_places=2,
        null=True,
        blank=True
    )
    annual_fee=models.DecimalField(
        max_digits=8, 
        decimal_places=2
    )
    due_date=models.DateField()

# Petroleum License
class PetroleumLicence(models.Model):
    ATP = 1
    PL = 2
    PPL = 3
    PFL = 4
    PCA = 5
    TYPE = (
        (ATP, _('Authority to Prospect')),
        (PL, _('Petroleum License')),
        (PPL, _('Petroleum Pipeline License')),
        (PFL, _('Petroleum Facility License')),
        (PCA, _('Prospective Commercial Area')),
    )

    type=models.PositiveSmallIntegerField(choices=TYPE)
    number=models.IntegerField()
    name=models.CharField(max_length=255)
    granted=models.DateField()
    term=models.IntegerField() #months
    extension_start=models.DateField(
        null=True,
        blank=True
    )
    extension_term=models.IntegerField() #months
    epa=models.ForeignKey(EPA, on_delete=models.RESTRICT, related_name='petroleum_licenses')

# Asset Area
class Area (models.Model):
    name=models.CharField(max_length=255)
    code=models.CharField(max_length=10)
    permit=models.ForeignKey(PetroleumLicence, on_delete=models.RESTRICT, related_name='areas')

# Document Type
class DocumentType (models.Model):
    name=models.CharField(max_length=255)
    code=models.CharField(max_length=10)
    drawing=models.BooleanField() #true for drawing

class DocumentSubType (models.Model):
    name=models.CharField(max_length=255)
    type=models.ForeignKey(DocumentType, on_delete=models.RESTRICT, related_name='sub_types')

# Document
class Document (models.Model):
    area=models.ForeignKey(Area, on_delete=models.RESTRICT, related_name='area_documents')
    type=models.ForeignKey(DocumentType, on_delete=models.RESTRICT, related_name='type_documents')
    sub_type=models.ForeignKey(DocumentSubType, null=True, blank=True, on_delete=models.RESTRICT, related_name='sub_type_documents')
    legacy_no=models.CharField(max_length=255, null=True, blank=True)

class DocumentRevision (models.Model):
    DRAFT = 1
    IFR = 2
    IFC = 3
    IFD = 4
    IFT = 5
    IFQ = 6
    IFI = 7
    ASBUILD = 99

    REASON = (
        (DRAFT, _('Draft')),
        (IFR, _('Issue for Review')),
        (IFC, _('Issue for Construction')),
        (IFD, _('Issue for Demolition')),
        (IFT, _('Issue for Tender')),
        (IFQ, _('Issue for Quotation')),
        (IFI, _('Issue for Information')),
        (ASBUILD, _('As Built')),
    )

    DRAFT = 1
    CURRENT = 2
    SUPERSEDED = 3
    OBSOLETE = 4
    ARCHIVED = 5

    STATUS = (
        (DRAFT, _('Draft')),
        (CURRENT, _('Current Revision')),
        (SUPERSEDED, _('Superseded')),
        (OBSOLETE, _('Obsolete')),
        (ARCHIVED, _('Archived')),
    )

    document=models.ForeignKey(Document, on_delete=models.CASCADE, related_name='revisions')
    revision=models.CharField(max_length=10)
    reason=models.PositiveSmallIntegerField(choices=REASON)
    status=models.PositiveSmallIntegerField(choices=STATUS)

class DocumentReference (models.Model):
    document=models.ForeignKey(Document, on_delete=models.CASCADE, related_name='reference_documents')
    reference_document=models.ForeignKey(Document, on_delete=models.RESTRICT, related_name='documents_referred_by')

# Assets
class AssetCategory (models.Model):
    name=models.CharField(max_length=255)

class LineContent (models.Model):
    name=models.CharField(max_length=255)
    code=models.CharField(max_length=10)

class LineRating (models.Model):
    name=models.CharField(max_length=255)
    code=models.CharField(max_length=10)
    
class AssetType (models.Model):
    category=models.ForeignKey(AssetCategory, on_delete=models.RESTRICT, related_name='category_types')
    name=models.CharField(max_length=255)
    code=models.CharField(max_length=10)
    
class Asset (models.Model):
    INSERVICE = 1
    OUTOFSERVICE = 2
    REMOVED = 3

    STATUS = (
        (INSERVICE, _('In Service')),
        (OUTOFSERVICE, _('Out of Service')),
        (REMOVED, _('Removed')),
    )

    type=models.ForeignKey(AssetType, on_delete=models.RESTRICT, related_name='type_assets')
    area=models.ForeignKey(Area, on_delete=models.RESTRICT, related_name='area_assets')
    sequential_no=models.IntegerField()
    suffix=models.CharField(max_length=3, null=True, blank=True)
    status=models.PositiveSmallIntegerField(choices=STATUS)
    legacy_no=models.CharField(max_length=255, null=True, blank=True)
    line_content=models.ForeignKey(LineContent, null=True, blank=True, on_delete=models.RESTRICT, related_name='line_content_assets')
    line_rating=models.ForeignKey(LineRating, null=True, blank=True, on_delete=models.RESTRICT, related_name='line_rating_assets')
    valve_spec=models.CharField(max_length=10, null=True, blank=True)
    size=models.IntegerField(null=True, blank=True)
    
class AssetHierachy (models.Model):
    asset=models.ForeignKey(Asset, on_delete=models.RESTRICT, related_name='parent')
    parent=models.ForeignKey(Asset, on_delete=models.RESTRICT, related_name='children')

class AssetDocumentReference (models.Model):
    asset=models.ForeignKey(Asset, on_delete=models.RESTRICT, related_name='asset_document_reference')
    document=models.ForeignKey(Document, on_delete=models.RESTRICT, related_name='assets_referred_by')

# Files
class File (models.Model):
    location=models.CharField(max_length=1000)
    ext=models.CharField(max_length=10)
    size=models.IntegerField(null=True, blank=True)
    name=models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}.{self.ext}"

    def link(self):
        return f"{self.location}{self.name}.{self.ext}"

class DocumentFile (models.Model):
    document=models.ForeignKey(Document, on_delete=models.RESTRICT, related_name='document_files')
    file=models.ForeignKey(File, on_delete=models.RESTRICT, related_name='file_document')

class Image (models.Model):
    file=models.ForeignKey(File, on_delete=models.RESTRICT, related_name='file_image')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class AssetImage (models.Model):
    image=models.ForeignKey(Asset, on_delete=models.RESTRICT, related_name='image_assets')
    asset=models.ForeignKey(Asset, on_delete=models.RESTRICT, related_name='asset_images')
    display=models.BooleanField(default=False) # Is this the main display picture of the asset
    nameplate=models.BooleanField(default=False) # Is this the nameplate picture

agf_wims/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# This module imports
from agf_assets.models import *


@login_required
def WellPage(request):
    wells = Well.objects.order_by('asset__area__region','status','name')
    regions = []

    region = ""
    for well in wells:
        if well.asset.area.region.name != region:
            region = well.asset.area.region.name
            regions.append(region)

    #regions = Region.objects.filter().order_by('name')

    context = {
        'wells' : wells,
        'regions' : regions,
    }

    return render(request, "agf_wims/wells.html", context)

agf_wims/templates/agf_wims/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="AGF Well Integrity Management System">

    <!-- Stylesheets -->
    <link 
        rel="stylesheet" 
        href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" 
        crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" 
        crossorigin="anonymous">
    <!-- <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">  -->
    <link 
        rel="stylesheet"  
        href="{% static 'css/wims.css' %}"
        type="text/css"/>

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" 
        crossorigin="anonymous">
    </script>
    {% block head %}{% endblock %}
</head>

<body class="d-flex flex-column h-100">

    <header class="fixed-top c-background">
        <nav class="navbar navbar-expand-md navbar-light p-0 c-navbarbackground">
            <a href="{% url 'home' %}" class="navbar-brand text-light p-0 c-navbarbackground">
                <div class="ps-3 py-1 c-navbarbackground">
                    <img src="{% static 'img/logo/transparent.png' %}" height="45" alt="" class="d-inline-block align-middle mr-2">
                </div>
            </a>
            <!-- Logo Text -->
            <a href="{% url 'wells' %}" class="navbar-brand text-light p-0 c-navbarbackground">
                <div class="py-1 pe-5 c-navbarbackground">
                    <span class="font-weight-bold align-middle c-base" style="color:white;">Well Integrity Management System</span>
                </div>
            </a>

            <button class="navbar-toggler c-navbutton" type="button" data-toggle="collapse" data-target="#navbarToggler"
                aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button> 

            <!-- Navbar -->
            <div class="collapse navbar-collapse" style="font-size: larger"  id="navbarToggler">
                <div class="navbar-nav ms-auto">
                    <a class="nav-item text-light nav-link ps-2 me-3" href="{% url 'home' %}">Home</a>
                    <a class="nav-item text-light nav-link ps-2 me-3" href="{% url 'wells' %}">Well Register</a>
                    <a class="nav-item text-light nav-link ps-2 me-3" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        </nav>

        <div id="alerts">
        </div>

        {% block header %}{% endblock %}
    </header>


    <!-- main -->
    <main id="main-body">
        {% block main %}{% endblock %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto pt-3">
        <div class="text-center py-2 bg-secondary">
            <span class="text-light"></span>
        </div>
    </footer>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" 
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" 
        crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
        crossorigin="anonymous"></script>
    
 
        <script>
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = cookies[i].trim();
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
        </script>
</body>

</html>

agf_wims/templates/agf_wims/blank.html
{% extends 'agf_documents/base.html' %}
{% block title %}
Name
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
<br>
<br>
<div class="container-fluid">
    <div class="row">
       
    </div>
</div>


{% endblock %}

agf_wims/templates/agf_wims/wells.html
{% extends 'agf_wims/base.html' %}
{% load mathfilters %}

{% block title %}
Well Register
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
<!-- Tabs -->
<ul class="nav nav-tabs">
    <li class="nav-item active"><a class="nav-link myTab active" data-toggle="tab" href="#all">All Regions</a></li>
    
    {% for region in regions %}
    <li class="nav-item"><a class="nav-link myTab" data-toggle="tab" href="#{{region}}">{{region}}</a></li>
    {% endfor %}
</ul>

<!-- Tab Content -->
<div class="tab-content">
    <!-- All Regions -->
    <div id="all" class="tab-pane fade show active">
        <div class="card" style="width: 100%;">
            <div class="card-body" style="height: 80vh; overflow-y: scroll; overflow-x: scroll;">
                <table class="table table-striped table-bordered table-sm">
                    <tr>
                        <th class="th-sm">Name</th>
                        <th>Type</th>
                        <th>Status</th>
                        <th>Longitude</th>
                        <th>Latitude</th>
                        <th>Elevation</th>
                        <th>Rotary Table</th>
                        <th>Total Depth</th>
                        <th>Spud Date</th>
                        <th>Rig Release Date</th>
                        <th>Plug Date</th>
                        <th>MAASP</th>
                        <th>MAWOP</th>
                    </tr>
                    <tbody>
                    {% for well in wells %}
                    <tr class="link" onclick="window.location.href='{% url 'asset' well.asset.id %}'">
                        <td>{{well.name}}</td>
                        <td>{{well.get_type_display}}</td>
                        <td>{{well.get_status_display}}</td>
                        
                        <td>
                            {{well.latitude|abs}}
                            {% if well.latitude < 0 %}
                            South
                            {% else %}
                            North
                            {% endif %}
                        </td>
                        <td>
                            {{well.longitude}}
                            {% if well.longitude < 0 %}
                            West
                            {% else %}
                            East
                            {% endif %}
                        </td>

                        <td>{{well.elevation|floatformat:2}}m</td>
                        <td>{{well.rotary_table|floatformat:2}}m</td>
                        <td>{{well.total_depth|floatformat:2}}m</td>
                        
                        <td>{{well.spud_date|date:"d/m/Y"}}</td>
                        <td>{{well.rig_release_date|date:"d/m/Y"}}</td>
                        <td>{{well.plug_date|date:"d/m/Y"}}</td>
                        
                        <td>
                            {% if well.MAASP %}
                            {{well.MAASP}}kPag
                            {% else %}
                            -
                            {% endif %}
                        </td>
                        <td>
                            {% if well.MAWOP %}
                            {{well.MAWOP}}kPag
                            {% else %}
                            -
                            {% endif %}
                        </td>
                        
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Iterate for each region -->
    {% for region in regions %}
    <div id="{{region}}" class="tab-pane fade">
        <div class="card" style="width: 100%;">
            <div class="card-body" style="height: 80vh; overflow-y: scroll; overflow-x: scroll;">
                <table class="table table-striped table-bordered table-sm">
                    <tr>
                        <th class="th-sm">Name</th>
                        <th>Type</th>
                        <th>Status</th>
                        <th>Longitude</th>
                        <th>Latitude</th>
                        <th>Elevation</th>
                        <th>Rotary Table</th>
                        <th>Total Depth</th>
                        <th>Spud Date</th>
                        <th>Rig Release Date</th>
                        <th>Plug Date</th>
                        <th>MAASP</th>
                        <th>MAWOP</th>
                    </tr>
                    <tbody>
                    {% for well in wells %}
                    {% if well.asset.area.region.name == region %}
                    <tr class="link" onclick="window.location.href='{% url 'asset' well.asset.id %}'">
                        <td>{{well.name}}</td>
                        <td>{{well.get_type_display}}</td>
                        <td>{{well.get_status_display}}</td>
                        
                        <td>
                            {{well.latitude|abs}}
                            {% if well.latitude < 0 %}
                            South
                            {% else %}
                            North
                            {% endif %}
                        </td>
                        <td>
                            {{well.longitude}}
                            {% if well.longitude < 0 %}
                            West
                            {% else %}
                            East
                            {% endif %}
                        </td>

                        <td>{{well.elevation|floatformat:2}}m</td>
                        <td>{{well.rotary_table|floatformat:2}}m</td>
                        <td>{{well.total_depth|floatformat:2}}m</td>
                        
                        <td>{{well.spud_date|date:"d/m/Y"}}</td>
                        <td>{{well.rig_release_date|date:"d/m/Y"}}</td>
                        <td>{{well.plug_date|date:"d/m/Y"}}</td>
                        
                        <td>
                            {% if well.MAASP %}
                            {{well.MAASP}}kPag
                            {% else %}
                            -
                            {% endif %}
                        </td>
                        <td>
                            {% if well.MAWOP %}
                            {{well.MAWOP}}kPag
                            {% else %}
                            -
                            {% endif %}
                        </td>
                        
                    </tr>
                    {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% endfor %}

</div>


{% endblock %}