agf/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.Index,  name='home'),
    path('profile', views.Profile,  name='profile'),

    # Built in
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),

    # Documents
    path('documents/', include('agf_documents.urls')),

    # Assets
    path('assets/', include('agf_assets.urls')),

    # HSE
    path('hse/', include('agf_hse.urls')),
    
    # Maintenance
    path('maintenance/', include('agf_maintenance.urls')),

    # Stores
    path('stores/', include('agf_stores.urls')),

    # WIMS
    path('wims/', include('agf_wims.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agf_documents/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    # Document Dashboard
    path('', views.IndexLogin.as_view(), name='documents'),

    # Document Page
    path('document/<int:id>/', views.DocumentPage, name='document'),

    path('document_new_revision/<int:id>/', views.NewDocumentRevision, name='document_new_revision'),
    path('document_new_reference/<int:id>/', views.NewDocumentReference, name='document_new_reference'),

    path('documet_create_public_link/<int:id>/', views.CreatePublicLink, name='documet_create_public_link'),
    path('public_link/<str:link>/', views.PublicLink, name='documet_public_link'),

    # Document Search
    path('search', views.Search, name='document_search'),

    # Create new Document
    path('create', views.Create, name='document_create'),
    

    # Admin Functions
    path('missing_files', views.MissingFiles), 
]

agf_documents/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

# Other module imports
from agf_assets.models import *

# Document Type
class DocumentType (models.Model):
    name=models.CharField(max_length=255)
    code=models.CharField(max_length=10)
    drawing=models.BooleanField() #true for drawing

    def __str__(self):
        return f"{self.name} ({self.code})"

    @property
    def name_code(self):
        return f"{self.name} ({self.code})"

class DocumentSubType (models.Model):
    name=models.CharField(max_length=255)
    type=models.ForeignKey(DocumentType, on_delete=models.RESTRICT, related_name='sub_types')
    
    def __str__(self):
        return f"{self.name}"

# Document
class Document (models.Model):
    area=models.ForeignKey(Area, on_delete=models.RESTRICT, related_name='area_documents')
    type=models.ForeignKey(DocumentType, on_delete=models.RESTRICT, related_name='type_documents')
    sub_type=models.ForeignKey(DocumentSubType, null=True, blank=True, on_delete=models.RESTRICT, related_name='sub_type_documents')
    sequential_no=models.IntegerField()
    suffix=models.CharField(max_length=10,null=True, blank=True)
    sheet=models.IntegerField(null=True, blank=True)
    name=models.CharField(max_length=255)
    legacy_no=models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.document_no

    @property
    def document_no(self):
        document_no = f"{self.area.code}-{self.type.code}-{self.sequential_no:04}"

        if self.suffix is not None:
            document_no += "-" + self.suffix
        
        if self.sheet is not None:
            document_no += f"-{self.sheet:02}"

        return document_no

    @property
    def area_code(self):
        return self.area.code

    def name_with_legacy(self):
        document_no = f"{self.area.code}-{self.type.code}-{self.sequential_no:04}"

        if self.suffix is not None:
            document_no += "-" + self.suffix

        if self.sheet is not None:
            document_no += f"-{self.sheet:02}"
            
        if self.legacy_no is None:
            return document_no
        else:
            return f"{document_no} ({self.legacy_no})"

    def my_sub_type_name_display(self):
        if self.sub_type is None:
            return "None"
        else:
            return self.sub_type.name

    def my_legacy_no_display(self):
        if self.legacy_no is None:
            return "-"
        else:
            return self.legacy_no

class DocumentRevision (models.Model):
    DRAFT = 1
    IFR = 2
    IFC = 3
    IFD = 4
    IFT = 5
    IFQ = 6
    IFI = 7
    IFU = 8
    IFH = 9
    IFComment = 10
    ASBUILD = 99

    REASON = (
        (DRAFT, _('Draft')),
        (IFI, _('Issue for Information')),
        (IFComment, _('Issue for Comment')),
        (IFR, _('Issue for Review')),
        (IFH, _('Issue for HAZOP')),
        (IFQ, _('Issue for Quotation')),
        (IFT, _('Issue for Tender')),
        (IFC, _('Issue for Construction')),
        (IFD, _('Issue for Demolition')),
        (IFU, _('Issue for Use')),
        (ASBUILD, _('As Built')),
    )

    DRAFT = 1
    CURRENT = 2
    SUPERSEDED = 3
    OBSOLETE = 4
    ARCHIVED = 5

    STATUS = (
        (DRAFT, _('Draft')),
        (CURRENT, _('Current Issue')),
        (SUPERSEDED, _('Superseded')),
        (OBSOLETE, _('Obsolete')),
        (ARCHIVED, _('Archived')),
    )

    document=models.ForeignKey(Document, on_delete=models.CASCADE, related_name='revisions')
    revision=models.CharField(max_length=10, null=True, blank=True)
    reason=models.PositiveSmallIntegerField(choices=REASON,null=True, blank=True)
    status=models.PositiveSmallIntegerField(choices=STATUS)
    
    def __str__(self):
        if self.revision is None:
            return self.document
        else:
            return f"{self.document}_{self.revision}"

    def my_revision_display(self):
        if self.revision is None:
            return "N/A"
        else:
            return self.revision

    def my_reason_display(self):
        if self.reason is None:
            return "-"
        else:
            return self.get_reason_display()

    def my_link_generator(self):
        count = self.document_files.count()
        if count == 1:
            df = self.document_files.first()
            file = df.file
            return file.url() 
        else:
            return "#"

    @property
    def my_link(self):
        count = self.document_files.count()
        if count == 1:
            df = self.document_files.first()
            file = df.file
            return file.url() 
        else:
            return "#"
        
    @property
    def file_name(self):
        count = self.document_files.count()
        if count == 1:
            df = self.document_files.first()
            file = df.file
            if file:
                return f"{file.name}.{file.ext}" 
            else: 
                return "Error"
        else:
            return f"{self.document} (multiple files)"

class DocumentReference (models.Model):
    document=models.ForeignKey(Document, on_delete=models.CASCADE, related_name='reference_documents')
    reference_document=models.ForeignKey(Document, on_delete=models.RESTRICT, related_name='documents_referred_by')

agf_documents/forms.py
from django import forms


from .models import *

from agf_assets.models import *

class CreateDocument(forms.Form):
    area = forms.ModelChoiceField(label='Area', queryset=Area.objects.all())
    type = forms.ModelChoiceField(label='Document Type', queryset=DocumentType.objects.all())
    sub_type = forms.ModelChoiceField(label='Document Sub-Type', queryset=DocumentSubType.objects.all(), required=False)
    name = forms.CharField(label='Document Name', max_length=255)
    legacy_no = forms.CharField(label='Legacy Number', max_length=255, required=False)
    sheets = forms.IntegerField(label='Sheets', required=False)

class CreateRevision(forms.Form):
    document = forms.ModelChoiceField(label='Document', queryset=Document.objects.all())
    revision = forms.CharField(label='Revision Number',max_length=10, required=False)
    reason = forms.IntegerField(label='Reason', required=False)
    status = forms.IntegerField(label='Status')
    file = forms.FileField()

class CreateDocumentReference(forms.Form):
    document = forms.ModelChoiceField(label='Document', queryset=Document.objects.all())
    reference = forms.ModelChoiceField(label='Reference Document', queryset=Document.objects.all())
    
class SearchDocument(forms.Form):
    name = forms.CharField(label='Document Name',max_length=255, required=False)
    area = forms.ModelChoiceField(label='Area', queryset=Area.objects.all(), required=False)
    type = forms.ModelChoiceField(label='Document Type', queryset=DocumentType.objects.all(), required=False)
    sub_type = forms.ModelChoiceField(label='Document Sub-Type', queryset=DocumentSubType.objects.all(), required=False)

agf_documents/templates/agf_documents/create.html
{% extends 'agf_documents/base.html' %}
{% block title %}
New Document
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <form action="{% url 'document_create' %}" method="POST">
                {% csrf_token %}
                <!--<table>
                    {{ form.as_table }}
                    <br><br>
                </table>-->
        
                <table>
                    <tr>
                        <th>
                            <label for="id_area">Area:</label>
                        </th>
                        <td>
                            <select name="area" required="" id="id_area">
                                <option value="" selected="">---------</option>
                                {% for area in areas %}
                                <option value="{{area.id}}">{{area.code}}: {{area.name}}</option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
        
                    <tr><td><br></td></tr>
                    
                    <tr>
                        <th>
                            Document <input type="radio" onclick="DocumentOrDrawing('document')" id="document" value="document">
                        </th>
                        <th>
                            Drawing <input type="radio" onclick="DocumentOrDrawing('drawing')" id="drawing" value="drawing">
                        </th>
                    </tr>
                    <tr>
                        <th>
                            <label for="id_type">Type:</label>
                        </th>
                        <td>
                            <select name="type" required="" id="id_type" onchange="TypeSelection()" required>
                            </select>
                        </td>
                    </tr>
                    <tr id="subTypeRow" style="display:none;">
                        <th><label for="id_sub_type">Sub-Type:</label></th>
                        <td>
                            <select name="sub_type" id="id_sub_type">
                                <option value="" selected="">---------</option>
                            </select>
                        </td>
                    </tr>
        
                    <tr><td><br></td></tr>
        
                    <tr>
                        <th><label for="id_name">Document Name:</label></th>
                        <td>
                            <input type="text" name="name" maxlength="255" required="" id="id_name">
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_legacy_no">Legacy Number:</label></th>
                        <td>
                            <input type="text" name="legacy_no" maxlength="255" id="id_legacy_no" placeholder="If required">
                        </td>
                    </tr>
                    <tr id="sheetsRow" style="display:none;">
                        <th>
                            <label for="id_sheets">Sheets:</label>
                        </th>
                        <td>
                            <input type="number" name="sheets" id="id_sheets" placeholder="If required">
                        </td>
                    </tr>
                </table>
                <br>
                <input class="btn btn-primary" type="submit" value="Submit">
            </form>
        </div>
    </div>
    
</div>

<script>
    var document = -1
    docEl = document.getElementById("document")
    drawEl = document.getElementById("drawing")

    typeSelectionEl = document.getElementById("id_type")

    subTypeSelectionEl = document.getElementById("id_sub_type")
    subTypeRowEl = document.getElementById("subTypeRow")

    sheetsSelectionEl = document.getElementById("id_sheets")
    sheetsRowEl = document.getElementById("sheetsRow")

    function DocumentOrDrawing(switchTo){
        if (switchTo == "document"){
            if (document != 1) {
                document = 1;
                docEl.checked = true;
                drawEl.checked = false;

                typeSelectionEl.options.length=0;
                typeSelectionEl.options.add(new Option("---------", ""))
                
                {% for type in types %}
                {% if not type.drawing %}
                typeSelectionEl.options.add(new Option("{{type.code}}: {{type.name}}", "{{type.id}}"))
                {% endif %}
                {% endfor %}

                sheetsRowEl.style.display = "none"
                sheetsSelectionEl.value=""
            }
        }
        if (switchTo == "drawing"){
            if (document != 0) {
                document = 0;
                docEl.checked = false;
                drawEl.checked = true;

                typeSelectionEl.options.length=0;
                typeSelectionEl.options.add(new Option("---------", ""))
                
                {% for type in types %}
                {% if type.drawing %}
                typeSelectionEl.options.add(new Option("{{type.code}}: {{type.name}}", "{{type.id}}"))
                {% endif %}
                {% endfor %}

                sheetsRowEl.style.display = "table-row"
            }
        }
    }

    function TypeSelection(){
        subTypeSelectionEl.options.length=0;
        subTypeSelectionEl.options.add(new Option("---------", ""))

        count = 0

        {% for sub_type in sub_types %}
        if({{sub_type.type.id}} == typeSelectionEl.value){
            count += 1
            subTypeSelectionEl.options.add(new Option("{{sub_type.name}}", "{{sub_type.id}}"))
        }
        {% endfor %}

        if(count > 0){
            subTypeRowEl.style.display = "table-row"
        } else {
            subTypeRowEl.style.display = "none"
        }
    }
</script>
{% endblock %}

agf_documents/templates/agf_documents/public.html
{% extends 'agf_documents/base.html' %}
{% block title %}
Document: {{document.document_no}}
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-4">
            <div class="card">
                <div class="card-body">
                    <h1>{{document.document_no}}</h1>
                    <a class="btn btn-primary" href="{{documentFile.file.url}}">Download</a>
                    <table class="table" style="width: auto;">
                        <tr>
                            <th>Document No.</th>
                            <td>{{document.document_no}}</td>
                        </tr>
                        {% if document.legacy_no is not None %}
                        <tr>
                            <th>Legacy Number</th>
                            <td>{{document.legacy_no}}</td>
                        </tr>
                        {% endif %}
                        <tr>
                            <th>Name</th>
                            <td>{{document.name}}</td>
                        </tr>
                        <tr>
                            <th>Type</th>
                            <td>{{document.type}}</td>
                        </tr>
                        {% if document.sub_type is not None %}
                        <tr>
                            <th>Sub-Type</th>
                            <td>{{document.sub_type}}</td>
                        </tr>
                        {% endif %}
                        <tr>
                            <th>Area</th>
                            <td>{{document.area}}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <!-- Revisions -->
            <div class="card">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr><th colspan="5"><h4><b>Document Revision</b></h4></th></tr>
                        <tr>
                            <th>Status</th>
                            <td>{{documentRevision.get_status_display}}</td>
                        </tr>
                        <tr>
                            <th>Revision</th>
                            <td>{{documentRevision.revision}}</td>
                        </tr>
                        <tr>
                            <th>Reason</th>
                            <td>{{documentRevision.get_reason_display}}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-xl-8 pb-3">
            <!-- Preview -->
            <div class="card mb-0" style="height:100%;">
                <div class="card-body">
                    {% if documentFile %}
                    <p class="link" style="text-align:right; position: absolute; right: 30px; top:30px;"><i class="fas fa-expand-arrows-alt fa-2x"></i></p>
                    <iframe src="{{documentFile.file.url}}#toolbar=0&navpanes=0" width="100%" height="100%"></iframe>
                    {% else %}
                        <p>No file available for preview</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}

agf_documents/templates/agf_documents/search.html
{% extends 'agf_documents/base.html' %}
{% block title %}
Document Search
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
<br>
<br>
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <form action="{% url 'document_search' %}" method="POST">
                {% csrf_token %}
                <!--<table>
                    {{ form.as_table }}
                </table>-->
                <table>
                    <tr>
                        <th>
                            <label for="id_area">Area:</label>
                        </th>
                        <td>
                            <select name="area" id="id_area">
                                <option value="" selected="">---------</option>
                                {% for area in areas %}
                                <option
                                    value="{{area.id}}"
                                    {% if area.id == area_selected.id %}
                                    selected
                                    {% endif %}
                                >
                                    {{area.code}}: {{area.name}}
                                </option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
        
                    <tr><td><br></td></tr>
                    
                    <tr>
                        <th>
                            Document
                            <input 
                                type="radio" 
                                onclick="DocumentOrDrawing('document')" 
                                id="document" 
                                value="document"
                                {% if type_selected %}
                                {% if not type_selected.drawing %}
                                checked
                                {% endif %}
                                {% endif %}
                            >
                        </th>
                        <th>
                            Drawing
                            <input 
                                type="radio" 
                                onclick="DocumentOrDrawing('drawing')" 
                                id="drawing" 
                                value="drawing"
                                {% if type_selected.drawing %}
                                checked
                                {% endif %}
                            >
                        </th>
                    </tr>
                    <tr>
                        <th>
                            <label for="id_type">Type:</label>
                        </th>
                        <td>
                            <select name="type" id="id_type" onchange="TypeSelection()">
                                {% if type_selected %}
                                    <option value="">---------</option>
                                    {% for type in types %}
                                    {% if type.drawing == type_selected.drawing %}
                                    <option value="{{type.id}}"
                                        {% if type_selected.id == type.id %}
                                        selected=""
                                        {% endif %}
                                    >
                                        {{type.code}}: {{type.name}}
                                    </option>
                                    typeSelectionEl.options.add(new Option("", ""))
                                    {% endif %}
                                    {% endfor %}
                                {% else %}
                                    <option value="" selected="">---------</option>
                                {% endif %}
                            </select>
                        </td>
                    </tr>
                    <tr 
                        id="subTypeRow" 
                        style="display:none;"
                    >
                        <th><label for="id_sub_type">Sub-Type:</label></th>
                        <td>
                            <select name="sub_type" id="id_sub_type">
                                <option value="" selected="">---------</option>
                            </select>
                        </td>
                    </tr>
        
                    <tr><td><br></td></tr>
        
                    <tr>
                        <th><label for="id_name">Document Name:</label></th>
                        <td>
                            <input 
                                type="text" 
                                name="name" 
                                maxlength="255" 
                                id="id_name"
                                {% if name %}
                                value = "{{name}}"
                                {% endif %}
                            >
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_legacy_no">Legacy Number:</label></th>
                        <td>
                            <input 
                                type="text" 
                                name="legacy_no" 
                                maxlength="255" 
                                id="id_legacy_no" 
                                placeholder="If required"
                                {% if legacy_no %}
                                value = "{{legacy_no}}"
                                {% endif %}
                            >
                        </td>
                    </tr>
                    
                </table>
                <br>
                <input class="btn btn-primary" type="submit" value="Submit">
            </form>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>Document</th>
                        <th>Name</th>
                        <th style="text-align: center;">Legacy Number</th>
                    </tr>
                </thead>
                <tbody>
                    {% for document in documents %}
                    <tr class="link" onclick="window.location.href='{% url 'document' document.id %}'">
                        <td>{{document.document_no}}</td>
                        <td>{{document.name}}</td>
                        <td style="text-align: center;">{{document.legacy_no}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    var document = -1
    docEl = document.getElementById("document")
    drawEl = document.getElementById("drawing")

    typeSelectionEl = document.getElementById("id_type")

    subTypeSelectionEl = document.getElementById("id_sub_type")
    subTypeRowEl = document.getElementById("subTypeRow")

    function DocumentOrDrawing(switchTo){
        if (switchTo == "document"){
            if (document != 1) {
                document = 1;
                docEl.checked = true;
                drawEl.checked = false;

                typeSelectionEl.options.length=0;
                typeSelectionEl.options.add(new Option("---------", ""))
                
                {% for type in types %}
                {% if not type.drawing %}
                typeSelectionEl.options.add(new Option("{{type.code}}: {{type.name}}", "{{type.id}}"))
                {% endif %}
                {% endfor %}
            }
        }
        if (switchTo == "drawing"){
            if (document != 0) {
                document = 0;
                docEl.checked = false;
                drawEl.checked = true;

                typeSelectionEl.options.length=0;
                typeSelectionEl.options.add(new Option("---------", ""))
                
                {% for type in types %}
                {% if type.drawing %}
                typeSelectionEl.options.add(new Option("{{type.code}}: {{type.name}}", "{{type.id}}"))
                {% endif %}
                {% endfor %}
            }
        }
    }

    function TypeSelection(){
        subTypeSelectionEl.options.length=0;
        subTypeSelectionEl.options.add(new Option("---------", ""))

        count = 0

        {% for sub_type in sub_types %}
        if({{sub_type.type.id}} == typeSelectionEl.value){
            count += 1
            subTypeSelectionEl.options.add(new Option("{{sub_type.name}}", "{{sub_type.id}}"))
        }
        {% endfor %}

        if(count > 0){
            subTypeRowEl.style.display = "table-row"
        } else {
            subTypeRowEl.style.display = "none"
        }
    }
</script>

{% endblock %}